# Generated by Django 4.1.7 on 2023-03-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMSUser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.CharField(
                choices=[(1, "ADMIN"), (2, "USER")], default="ADMIN", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="modified_by",
            field=models.CharField(
                choices=[(1, "ADMIN"), (2, "USER")], default="ADMIN", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="user", name="is_email_verified", field=models.BooleanField(),
        ),
    ]
