# Generated by Django 4.1.7 on 2023-03-19 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMSUser", "0002_user_created_by_user_modified_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateField(default=datetime.date(2023, 3, 19)),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_terminated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="modified_date",
            field=models.DateField(default=datetime.date(2023, 3, 19)),
        ),
        migrations.AlterField(
            model_name="user",
            name="version_number",
            field=models.IntegerField(default=0),
        ),
    ]
