# Generated by Django 4.1.7 on 2023-03-19 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMSUser", "0003_alter_user_created_date_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 19, 18, 26, 50, 136560, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="modified_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 19, 18, 26, 50, 136560, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
