# Generated by Django 4.1.7 on 2023-03-19 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("LMSUser", "0004_alter_user_created_date_alter_user_modified_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="modified_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
