# Generated by Django 4.1.7 on 2023-03-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMSUser", "0005_alter_user_created_date_alter_user_modified_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
