# Generated by Django 4.1.7 on 2023-03-22 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LMSUser", "0006_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("middle_name", models.CharField(blank=True, max_length=60, null=True)),
                ("phone", models.CharField(max_length=10)),
                ("password1", models.CharField(max_length=10)),
                ("password2", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_terminated", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.CharField(
                        choices=[(1, "ADMIN"), (2, "USER")],
                        default="ADMIN",
                        max_length=5,
                    ),
                ),
                ("created_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "modified_by",
                    models.CharField(
                        choices=[(1, "ADMIN"), (2, "USER")],
                        default="ADMIN",
                        max_length=5,
                    ),
                ),
                ("modified_date", models.DateField(default=django.utils.timezone.now)),
                ("version_number", models.IntegerField(default=0)),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="User",),
    ]
