# Generated by Django 4.1.7 on 2023-03-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LMSUser", "0007_customuser_delete_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="password1",),
        migrations.RemoveField(model_name="customuser", name="password2",),
    ]
