# Generated by Django 4.1.7 on 2023-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicdetails",
            name="salary_type",
            field=models.CharField(
                choices=[(2, "Bussiness"), (3, "Student"), (1, "Salaried")],
                max_length=15,
            ),
        ),
    ]
