# Generated by Django 4.1.7 on 2023-04-08 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0002_alter_basicdetails_salary_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("version_number", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="basicdetails",
            name="salary_type",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loan.salarytypes",
            ),
        ),
    ]
