# Generated by Django 4.1.7 on 2023-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0003_salarytypes_alter_basicdetails_salary_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicdetails",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
