# Generated by Django 4.1.7 on 2023-04-24 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0004_basicdetails_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.BinaryField()),
                (
                    "file_format",
                    models.CharField(
                        help_text="Stores the type of document i.e, pdf, jpeg, jpg, etc.",
                        max_length=6,
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="Store the name of the file.", max_length=60
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="Store the type of document uploaded. ex: Address Proof, income proof",
                        max_length=60,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.CharField(max_length=256)),
                (
                    "modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("modified_by", models.CharField(max_length=256)),
                ("version_number", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="basicdetails",
            name="created_by",
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="basicdetails",
            name="modified_by",
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
