# Generated by Django 4.1.7 on 2023-04-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0005_documents_basicdetails_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="basicdetails", name="loan_type",),
        migrations.RemoveField(model_name="basicdetails", name="salary_type",),
        migrations.AddField(
            model_name="basicdetails",
            name="loan_type",
            field=models.ManyToManyField(to="loan.loantypes"),
        ),
        migrations.AddField(
            model_name="basicdetails",
            name="salary_type",
            field=models.ManyToManyField(to="loan.salarytypes"),
        ),
    ]
