# Generated by Django 4.1.7 on 2023-04-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0006_remove_basicdetails_loan_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="basicdetails", name="loan_type",),
        migrations.RemoveField(model_name="basicdetails", name="salary_type",),
        migrations.AddField(
            model_name="basicdetails",
            name="loan_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loan.loantypes",
            ),
        ),
        migrations.AddField(
            model_name="basicdetails",
            name="salary_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loan.salarytypes",
            ),
        ),
    ]
