# Generated by Django 4.1.7 on 2023-04-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0007_remove_basicdetails_loan_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents", name="file", field=models.FileField(upload_to=""),
        ),
    ]
