# Generated by Django 4.1.7 on 2023-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0009_documents_loan_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="basicdetails", name="zipcode1",),
        migrations.RemoveField(model_name="basicdetails", name="zipcode2",),
        migrations.AlterField(
            model_name="basicdetails",
            name="address1",
            field=models.CharField(
                max_length=512, verbose_name="Address1 will store the Current Address"
            ),
        ),
        migrations.AlterField(
            model_name="basicdetails",
            name="address2",
            field=models.CharField(
                max_length=512, verbose_name="Address1 will store the Permanent Address"
            ),
        ),
        migrations.AlterField(
            model_name="basicdetails",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
