# Generated by Django 4.1.7 on 2023-04-26 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0010_remove_basicdetails_zipcode1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicdetails",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator("0.01")],
            ),
        ),
    ]
