# Generated by Django 4.1.7 on 2023-04-26 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0011_alter_basicdetails_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicdetails",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documents", unique_together={("document_type", "loan_id")},
        ),
    ]
