# Generated by Django 4.1.7 on 2023-04-27 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0012_alter_basicdetails_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicdetails",
            name="tenure",
            field=models.IntegerField(
                default=12,
                help_text="Minimum Tenure should be 12 months and Maximum Tensure will be 360 months",
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
