# Generated by Django 4.1.7 on 2023-04-28 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0013_basicdetails_tenure"),
    ]

    operations = [
        migrations.AddField(
            model_name="loantypes",
            name="down_payment",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="loantypes",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=7.2,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(7.2),
                    django.core.validators.MaxValueValidator(15.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="basicdetails",
            name="tenure",
            field=models.IntegerField(
                default=12,
                help_text="Minimum Tenure should be 12 months and Maximum Tensure will be 360 months",
                validators=[
                    django.core.validators.MaxValueValidator(360),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
